services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  nest:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
    environment:
      - MONGO_DB_PATH=mongodb://root:example@mongo:27017/
      - PORT=3000
    # Run a command against the development stage of the image
    command: npm run start:prod
    ports:
      - 3000:3000
    depends_on:
      - mongo
